import { PgDatabase } from "drizzle-orm/pg-core";
export declare function restoreItemCommand(itemId: string, itemType: "CATEGORY" | "INCOME_SOURCE" | "BANK_ACCOUNT", tenantId: string, appId: string, userId: string, dbClient?: PgDatabase<any, any, any>): Promise<{
    createdAt: Date;
    createdBy: string;
    updatedAt: Date;
    updatedBy: string;
    archivedAt: Date | null;
    archivedBy: string | null;
    tenantId: string;
    appId: string;
    id: string;
    name: string;
    lastKnownBalance: string;
    unbudgetedBuffer: string;
} | {
    createdAt: Date;
    createdBy: string;
    updatedAt: Date;
    updatedBy: string;
    archivedAt: Date | null;
    archivedBy: string | null;
    tenantId: string;
    appId: string;
    id: string;
    name: string;
    type: "REGULAR" | "GOAL" | "EVERYDAY";
    isCommitted: boolean;
    monthlyAmount: string | null;
    everydayAllowanceAmount: string | null;
    isDefaultExcess: boolean;
    rolloverRule: "ROLLOVER" | "SWEEP" | "RESET";
    isDefaultSavings: boolean;
    icon: string | null;
    colour: string | null;
    budgetFrequency: string | null;
    bankAccountId: string | null;
    lastNotifiedAt: Date | null;
} | {
    createdAt: Date;
    createdBy: string;
    updatedAt: Date;
    updatedBy: string;
    archivedAt: Date | null;
    archivedBy: string | null;
    tenantId: string;
    appId: string;
    id: string;
    name: string;
    amount: string;
    receivingAccountId: string | null;
    rrule: string | null;
    startDate: string | null;
    endDate: string | null;
}>;
//# sourceMappingURL=restore-item.command.d.ts.map